language: python
python:
 - "3.5"
 - "3.5-dev"
 - "3.6"
 - "3.6-dev"
 - "3.7-dev"
 - "nightly"
install:
 - pip install pylint requests
script:
 - python3 -m pylint -r n -d bad-whitespace,missing-docstring,too-many-arguments,locally-disabled,line-too-long,too-many-public-methods,too-many-lines,too-many-instance-attributes,too-many-locals,too-many-branches,too-many-statements instaloader
